### ISSUE TITLE
发件人名字的问题咨询一下。

### ISSUE THREAD

**Issue by shima-park** [aliyun-sdk/mail-go#1]
我按照示例中的代码，替换成了公司对应的邮箱账号，发送后收到了邮件，
但是发件人的名字没有显示为预料中的 [test boy]，而是[通用通知]。
用我自己的邮箱发送测试后，显示的名字为我自己的真实姓名。
请问是否是aliyun的smtp服务做了特殊处理还是什么其他的情况。
```
client := smtp.New("smtp.xxx.aliyun.com", "user", "pass")
err := client.Send(
		smtp.From("test boy"),
		smtp.Subject("我的测试邮件标题"),
		smtp.SendTo("test@xxx.com"),
		smtp.Content(smtp.Plain, "我的测试邮件"),
	)
```

**Comment by letsfire** [comment]
不会吧，我测试了，发送，抄送，密送，发件人名称是test boy，你再试试

**Comment by shima-park** [comment]
同样的代码，我只更换了smtp服务器地址和验证登陆的账号密码，名字没有预期显示为传入的。
不知道是不是aliyun的smtp服务器做了什么安全限制之类，这块你知道吗

smtp服务器：smtp.qiye.aliyun.com
验证登陆的邮箱是公司阿里云的企业版邮箱
![image](https://user-images.githubusercontent.com/4186507/77392319-9bf1d400-6dd5-11ea-95e2-0eef1b471668.png)

smtp服务: smtp.163.com
验证登陆的邮箱是我的163邮箱
![image](https://user-images.githubusercontent.com/4186507/77392379-bf1c8380-6dd5-11ea-82e3-b27856cbf9bd.png)

**Comment by letsfire** [comment]
额，这个不了解，我测试的是阿里云的邮件推送产品 https://www.aliyun.com/product/directmail
你是个人的阿里云企业邮箱吧，那应该是被处理了，看看你企业邮箱控制台是不是有配置，没有的话估计是被强制修改了

**Comment by letsfire** [comment]
我用邮件推送产品发出，阿里云企业邮箱接受是正常的，估计阿里云作为SMTP发件人的时候强制修改了协议

**Comment by shima-park** [comment]
嗯，目前看下来应该是它内部做了处理。我们换了163的smtp服务来避免这个发件人名字不能修改的问题。
